export type SeedCustomer = {
  firstName: string;
  lastName: string;
  email?: string;
  phone?: string;
  notes?: string;
  visitsCount: number;
  spentCents: number;
};

export const SEED_CUSTOMERS: ReadonlyArray<SeedCustomer> = [
  {
    firstName: "Henri",
    lastName: "Aubert",
    email: "h.aubert@orange.fr",
    phone: "06 12 34 56 78",
    notes: "Habitué — table près de la fenêtre",
    visitsCount: 24,
    spentCents: 286400,
  },
  {
    firstName: "Claire",
    lastName: "Aubert",
    phone: "06 12 34 56 79",
    notes: "Allergie aux fruits à coque",
    visitsCount: 24,
    spentCents: 286400,
  },
  {
    firstName: "Cabinet",
    lastName: "Lefèvre",
    email: "contact@lefevre-avocats.fr",
    phone: "01 42 60 18 22",
    notes: "Déjeuners d'affaires — facturer cabinet",
    visitsCount: 18,
    spentCents: 412300,
  },
  {
    firstName: "Hiroshi",
    lastName: "Tanaka",
    email: "h.tanaka@gmail.com",
    phone: "07 88 21 09 14",
    notes: "Préfère le menu dégustation",
    visitsCount: 6,
    spentCents: 89500,
  },
  {
    firstName: "Léa",
    lastName: "Cohen-Sabban",
    email: "lea.cs@protonmail.com",
    phone: "06 73 45 12 88",
    notes: "Pas de porc",
    visitsCount: 11,
    spentCents: 154200,
  },
  {
    firstName: "Pierre",
    lastName: "Reverdin",
    phone: "06 09 87 65 43",
    notes: "Anniversaire le 14 mars",
    visitsCount: 9,
    spentCents: 132800,
  },
  {
    firstName: "Famille",
    lastName: "Dussart",
    email: "dussart.famille@free.fr",
    phone: "01 45 67 89 23",
    visitsCount: 4,
    spentCents: 76200,
  },
  {
    firstName: "Anne",
    lastName: "Beaumont",
    email: "anne.beaumont@me.com",
    phone: "06 22 33 44 55",
    notes: "Sommelière — adore les vins nature",
    visitsCount: 14,
    spentCents: 218900,
  },
  { firstName: "Marc", lastName: "Tessier", phone: "06 78 90 12 34", visitsCount: 2, spentCents: 28400 },
  {
    firstName: "Isabelle",
    lastName: "Granger",
    email: "i.granger@bnpparibas.com",
    phone: "06 11 22 33 44",
    notes: "Banque — souvent 8 couverts",
    visitsCount: 16,
    spentCents: 342100,
  },
  {
    firstName: "Olivier",
    lastName: "Vasseur",
    email: "o.vasseur@gmail.com",
    phone: "07 56 78 90 12",
    visitsCount: 7,
    spentCents: 98600,
  },
  {
    firstName: "Sophie",
    lastName: "Marchetti",
    phone: "06 45 67 89 01",
    notes: "Végétarienne",
    visitsCount: 5,
    spentCents: 64200,
  },
  {
    firstName: "Thomas",
    lastName: "Bouchard",
    email: "tbouchard@hotmail.fr",
    phone: "06 89 12 34 56",
    visitsCount: 3,
    spentCents: 41800,
  },
  {
    firstName: "Élise",
    lastName: "Rambert",
    email: "elise.rambert@gmail.com",
    phone: "07 12 34 56 78",
    notes: "Critique gastronomique — Le Figaro",
    visitsCount: 8,
    spentCents: 162400,
  },
  { firstName: "Jean-Paul", lastName: "Lhermitte", phone: "06 34 56 78 90", visitsCount: 12, spentCents: 184200 },
  {
    firstName: "Camille",
    lastName: "Vidal",
    email: "c.vidal@outlook.fr",
    phone: "06 67 89 01 23",
    visitsCount: 6,
    spentCents: 82400,
  },
  {
    firstName: "Antoine",
    lastName: "Berthier",
    email: "a.berthier@axa.fr",
    phone: "01 56 78 90 12",
    notes: "Réunions équipe AXA",
    visitsCount: 10,
    spentCents: 196300,
  },
  { firstName: "Margaux", lastName: "Faure", phone: "06 90 12 34 56", visitsCount: 3, spentCents: 38900 },
  {
    firstName: "Vincent",
    lastName: "Pasquier",
    email: "v.pasquier@gmail.com",
    phone: "07 23 45 67 89",
    visitsCount: 5,
    spentCents: 71200,
  },
  {
    firstName: "Béatrice",
    lastName: "Saint-Clair",
    email: "bsc@me.com",
    phone: "06 56 78 90 12",
    notes: "Amie de Léa",
    visitsCount: 19,
    spentCents: 264800,
  },
  {
    firstName: "Famille",
    lastName: "Nakamura",
    phone: "06 78 12 34 56",
    notes: "Touristes — anglais",
    visitsCount: 1,
    spentCents: 18400,
  },
  {
    firstName: "Raphaël",
    lastName: "Dorian",
    email: "raphael.dorian@gmail.com",
    phone: "06 01 23 45 67",
    visitsCount: 7,
    spentCents: 112300,
  },
  {
    firstName: "Hélène",
    lastName: "Moutarde",
    phone: "06 89 01 23 45",
    notes: "Anniversaire mariage 12/06",
    visitsCount: 4,
    spentCents: 68400,
  },
  {
    firstName: "Stéphane",
    lastName: "Carel",
    email: "s.carel@laposte.net",
    phone: "06 12 90 78 56",
    visitsCount: 2,
    spentCents: 24600,
  },
  {
    firstName: "Mathilde",
    lastName: "Esposito",
    email: "m.esposito@gmail.com",
    phone: "07 89 56 23 41",
    notes: "Photographe — autorise les photos",
    visitsCount: 6,
    spentCents: 89200,
  },
  { firstName: "Jérôme", lastName: "Bercot", phone: "06 45 12 78 90", visitsCount: 8, spentCents: 124500 },
  {
    firstName: "Caroline",
    lastName: "Vauthier",
    email: "c.vauthier@hermes.fr",
    phone: "01 40 17 47 17",
    notes: "Direction Hermès",
    visitsCount: 13,
    spentCents: 312800,
  },
  { firstName: "Xavier", lastName: "Lemoine", phone: "06 67 23 89 01", visitsCount: 3, spentCents: 42800 },
];
