import { writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

process.env.AUTH_SECRET = process.env.AUTH_SECRET ?? "codegen-placeholder-secret-0123456789";
process.env.NODE_ENV = process.env.NODE_ENV ?? "development";
process.env.LOG_LEVEL = process.env.LOG_LEVEL ?? "silent";

const here = dirname(fileURLToPath(import.meta.url));
const apiSrc = resolve(here, "../../../apps/api/src");
const outFile = resolve(here, "../src/generated.ts");

const BANNER = "// AUTO-GENERATED by packages/types/scripts/gen.ts — DO NOT EDIT.\n\n";
const PLACEHOLDER =
  BANNER +
  "// Codegen ran but the upstream API failed to produce an OpenAPI document.\n" +
  "// See README. Restart codegen once the API spec endpoint returns 200.\n\n" +
  "export type paths = Record<string, never>;\n" +
  "export type components = { schemas: Record<string, never> };\n" +
  "export type operations = Record<string, never>;\n";

async function generate(): Promise<{ ok: true; ts: string; pathCount: number } | { ok: false; reason: string }> {
  try {
    const { createApp } = await import(`${apiSrc}/app.ts`);
    const { OPENAPI_DOC_CONFIG } = await import(`${apiSrc}/openapi.ts`);
    const { generateSpecs } = await import("hono-openapi");
    const openapiTSModule = await import("openapi-typescript");
    const openapiTS = openapiTSModule.default;
    const astToString = openapiTSModule.astToString;

    const app = createApp();
    const doc = await generateSpecs(app, { documentation: OPENAPI_DOC_CONFIG });

    const ast = await openapiTS(doc as Parameters<typeof openapiTS>[0]);
    const ts = astToString(ast);
    const pathCount = Object.keys(
      (doc as { paths?: Record<string, unknown> }).paths ?? {},
    ).length;
    return { ok: true, ts, pathCount };
  } catch (err) {
    const reason = err instanceof Error ? err.message : String(err);
    return { ok: false, reason };
  }
}

async function main(): Promise<void> {
  const result = await generate();
  if (result.ok) {
    await writeFile(outFile, BANNER + result.ts, "utf8");
    console.log(`[types] wrote ${outFile} (${result.pathCount} paths)`);
    return;
  }
  await writeFile(outFile, PLACEHOLDER, "utf8");
  console.error(`[types] WARNING: codegen fell back to placeholder. Reason: ${result.reason}`);
  console.error(
    "[types] Aliases will resolve to never until the API OpenAPI generator is healthy.",
  );
}

main().catch((err: unknown) => {
  console.error("[types] codegen crashed:", err);
  process.exit(1);
});
